# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.IntegerField(default=123, unique=True, verbose_name='邮箱'),
            preserve_default=False,
        ),
    ]
